const pluginQuery = require('@tanstack/eslint-plugin-query');
const typescriptEslint = require('@typescript-eslint/eslint-plugin');
const tsParser = require('@typescript-eslint/parser');
const { defineConfig } = require('eslint/config');
const importX = require('eslint-plugin-import-x');
const prettier = require('eslint-plugin-prettier');
const react = require('eslint-plugin-react');
const reactHooks = require('eslint-plugin-react-hooks');
const { createTypeScriptImportResolver } = require('eslint-import-resolver-typescript');
const globals = require('globals');
const confusingGlobals = require('confusing-browser-globals');

module.exports = [
  reactHooks.configs.flat.recommended,
  ...pluginQuery.configs['flat/recommended'],
  defineConfig({
    files: ['**/*.js', '**/*.ts', '**/*.tsx'],
    plugins: {
      react,
      prettier,
      'import-x': importX,
      '@typescript-eslint': typescriptEslint,
    },
    languageOptions: { globals: { ...globals.browser, ...globals.node }, parser: tsParser },
    settings: {
      react: { version: 'detect' },
      'import-x/extensions': ['.js', '.ts', '.tsx', '.json'],
      'import-x/resolver-next': [createTypeScriptImportResolver()],
      'import-x/ignore': ['node_modules', '\.(scss|svg|json)$'],
    },
    rules: {
      curly: ['error', 'multi-line'],
      'arrow-body-style': ['error'],
      strict: ['error', 'never'],
      'no-useless-computed-key': ['error'],
      'no-useless-rename': ['error'],
      'no-var': ['error'],
      'object-shorthand': ['error'],
      'prefer-const': ['error'],
      'prefer-rest-params': ['error'],
      'prefer-spread': ['error'],
      'prefer-template': ['error'],
      'no-delete-var': ['error'],
      'no-shadow': ['error'],
      'no-shadow-restricted-names': ['error'],
      'no-undef-init': ['error'],
      'new-cap': ['error'],
      'no-bitwise': ['error'],
      'no-lonely-if': ['error'],
      'no-multi-assign': ['error'],
      'no-nested-ternary': ['error'],
      'no-unneeded-ternary': ['error', { defaultAssignment: false }],
      'one-var': ['error', 'never'],
      'operator-assignment': ['error', 'never'],
      'prefer-exponentiation-operator': ['error'],
      'prefer-object-spread': ['error'],
      'for-direction': ['error'],
      'getter-return': ['error'],
      'no-async-promise-executor': ['error'],
      'no-compare-neg-zero': ['error'],
      'no-cond-assign': ['error', 'always'],
      'no-console': ['warn'],
      'no-constant-condition': ['warn'],
      'no-control-regex': ['error'],
      'no-debugger': ['warn'],
      'no-dupe-else-if': ['error'],
      'no-duplicate-case': ['error'],
      'no-empty': ['error'],
      'no-empty-character-class': ['error'],
      'no-ex-assign': ['error'],
      'no-extra-boolean-cast': ['error', { enforceForLogicalOperands: true }],
      'no-inner-declarations': ['error'],
      'no-invalid-regexp': ['error'],
      'no-irregular-whitespace': ['error', { skipStrings: false }],
      'no-loss-of-precision': ['error'],
      'no-misleading-character-class': ['error'],
      'no-promise-executor-return': ['error'],
      'no-prototype-builtins': ['error'],
      'no-regex-spaces': ['error'],
      'no-sparse-arrays': ['error'],
      'no-unsafe-finally': ['error'],
      'no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
      'no-useless-backreference': ['error'],
      'use-isnan': ['error', { enforceForIndexOf: true }],
      'valid-typeof': ['error', { requireStringLiterals: true }],
      'array-callback-return': ['error'],
      'block-scoped-var': ['error'],
      'consistent-return': ['error'],
      'default-case': ['error'],
      'default-case-last': ['error'],
      'default-param-last': ['error'],
      'dot-notation': ['error'],
      eqeqeq: ['error'],
      'guard-for-in': ['error'],
      'no-alert': ['warn'],
      'no-case-declarations': ['error'],
      'no-else-return': ['error', { allowElseIf: false }],
      'no-empty-pattern': ['error'],
      'no-eval': ['error'],
      'no-extend-native': ['error'],
      'no-fallthrough': ['error'],
      'no-global-assign': ['error'],
      'no-implicit-coercion': ['error', { disallowTemplateShorthand: true }],
      'no-implied-eval': ['error'],
      'no-lone-blocks': ['error'],
      'no-multi-str': ['error'],
      'no-new': ['error'],
      'no-new-func': ['error'],
      'no-new-wrappers': ['error'],
      'no-octal': ['error'],
      'no-proto': ['error'],
      'no-return-assign': ['error', 'always'],
      'no-script-url': ['error'],
      'no-self-assign': ['error'],
      'no-self-compare': ['error'],
      'no-sequences': ['error', { allowInParentheses: false }],
      'no-throw-literal': ['error'],
      'no-unused-expressions': ['error'],
      'no-useless-catch': ['error'],
      'no-useless-concat': ['error'],
      'no-useless-escape': ['error'],
      'no-useless-return': ['error'],
      'no-void': ['error'],
      'prefer-promise-reject-errors': ['error'],
      'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
      'require-await': ['error'],
      'no-restricted-globals': ['error', ...confusingGlobals],

      // prettier
      'prettier/prettier': ['error'],

      // react
      'react/jsx-no-useless-fragment': ['error', { allowExpressions: true }],
      'react/no-unstable-nested-components': ['error', { allowAsProps: true }],
      'react/jsx-boolean-value': ['error'],
      'react/jsx-no-duplicate-props': ['error'],
      'react/no-deprecated': ['error'],
      'react/self-closing-comp': ['error'],
      'react/jsx-no-comment-textnodes': ['error'],
      'react/no-children-prop': ['error'],
      'react/void-dom-elements-no-children': ['error'],
      'react/jsx-curly-brace-presence': ['error'],
      'react/button-has-type': ['error'],
      'react/jsx-fragments': ['error', 'syntax'],
      'react/jsx-no-constructed-context-values': ['error'],

      // react-hooks
      'react-hooks/rules-of-hooks': ['error'],
      'react-hooks/exhaustive-deps': ['error'],

      // import-x
      'import-x/no-duplicates': ['error'],
      'import-x/newline-after-import': ['error'],
      'import-x/no-named-default': ['error'],
      'import-x/no-self-import': ['error'],
      'import-x/no-cycle': ['error', { maxDepth: 1 }],
      'import-x/no-useless-path-segments': ['error', { noUselessIndex: true, commonjs: true }],
      'import-x/order': [
        'error',
        {
          named: true,
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],

      // @typescript-eslint
      '@typescript-eslint/method-signature-style': ['error'],
      '@typescript-eslint/no-array-constructor': ['error'],
      '@typescript-eslint/no-explicit-any': ['error'],
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/no-unused-vars': ['warn', { varsIgnorePattern: '^_' }],
      '@typescript-eslint/prefer-as-const': ['error'],
      '@typescript-eslint/no-unsafe-declaration-merging': 'error',
    },
  }),
];
